### ISSUE TITLE
It doesn't work?

### ISSUE THREAD

**Issue by Subfader** [mrgrain/atom-altgr#1]
v0.1.0 in atom 1.8.0 doesn't fix anything. I still cannot type "\".

**Comment by Judejvlr** [comment]
Don't work correctly.. I cannot type '\' 
@mrgrain Help pleasee!! :$

**Comment by mrgrain** [comment]
Ah yes, sorry. This package is abandoned. It's a shame Atom still is isn't capable of handling it.

**Comment by Marcuslins** [comment]
In my ATOM Editor can not add the "/".
I would like a help to solve this problem

**Comment by mrgrain** [comment]
@Marcuslins Feel free to fork and take over the project
